### ISSUE TITLE
Signing up to Blip does not work

### ISSUE THREAD

**Issue by mrinnetmaki** [Sensotrend/sensotrend-tidepool#1]
After setting up the servers and running the runservers script I can access Blip at http://127.0.0.1:3000/, but signing up (http://127.0.0.1:3000/#/signup) gives me an error:
`POST http://localhost:8009/auth/user 500 (Internal Server Error)`

**Comment by mrinnetmaki** [comment]
server.log indicates

```
{"name":"styx","hostname":"tidepool-vm","pid":13826,"srcFile":"rules.js","level":40,"err":{"message":"connect ECONNREFUSED","name":"Error","stack":"Error: connect ECONNREFUSED\n at exports._errnoException (util.js:746:11)\n at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)","code":"ECONNREFUSED"},"msg":"Problem when forwarding request[/user] to [http://localhost:9107]","time":"2015-10-20T06:58:35.036Z","v":0}
```

**Comment by mrinnetmaki** [comment]
The POST request to http://localhost:8009/auth/user reports

> Problem!!!

**Comment by mrinnetmaki** [comment]
Not sure what the root cause was, but all works when tools are being set up with vagrant scripts (root user) and git repos set up and compiled by vagrant user. See 7fa6b33fb50eda14b7a547eb95efb7a90e819ca0.
